version: '3.6'
services:

  memcached:
    image: memcached
    networks:
      static_wbs:
        ipv4_address: 172.18.239.2

  redis:
    image: redis
    networks:
      static_wbs:
        ipv4_address: 172.18.239.3

  nginx:
    build:
      context: ./environment/nginx
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
    networks:
      static_wbs:
        ipv4_address: 172.18.239.4

  php_build:
    image: composer
    volumes:
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./vendor:/app/vendor
    command: composer install --ignore-platform-reqs
    networks:
      static_wbs:
        ipv4_address: 172.18.239.240

  php:
    depends_on:
      - php_build
      - mysql
    build:
      context: ./environment/php
    volumes:
      - ./:/var/www/html
    networks:
      static_wbs:
        ipv4_address: 172.18.239.5

  mysql:
    image: mysql:5.7
    volumes:
      - ./environment/mysql/sql:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    networks:
      static_wbs:
        ipv4_address: 172.18.239.6

  rabbitmq:
    image: rabbitmq:3.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=${DB_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${DB_PASSWORD}
    networks:
      static_wbs:
        ipv4_address: 172.18.239.7

volumes:
  dbdata:

networks:
  static_wbs:
    ipam:
      config:
      -
        subnet: 172.18.239.0/24
